=== Accredifysg/schemata/src/sg/gov/acra/bizfiles/profiles/limited-liability-partnership/1.0/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://cdn.uat.accredify.io/schema/acra/bizfiles/profiles/limited-liability-partnership/1.0/schema.json",
  "type": "object",
  "properties": {
    "entityName": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/entityName"
    },
    "formerNames": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/formerNames"
    },
    "uen": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/uen"
    },
    "registrationDate": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
    },
    "status": {
      "type": "string"
    },
    "statusDate": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
    },
    "address": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/address"
    },
    "changeOfNameDate": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
    },
    "changeOfAddressDate": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
    },
    "annualDeclarationDate": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
    },
    "activities": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/activities"
    },
    "conversionMessage": {
      "type": "string"
    },
    "partners": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/person"
          }
        ],
        "properties": {
          "appointmentDate": {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
          },
          "withdrawalDate": {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
          }
        },
        "required": [
          "appointmentDate"
        ]
      }
    },
    "partnersUnder18A": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/person"
          }
        ],
        "properties": {
          "appointmentDate": {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
          },
          "withdrawalDate": {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
          }
        },
        "required": [
          "appointmentDate"
        ]
      }
    },
    "managers": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/person"
          }
        ],
        "properties": {
          "appointmentDate": {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
          },
          "withdrawalDate": {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
          }
        },
        "required": [
          "appointmentDate"
        ]
      }
    },
    "liquidators": {
      "type": "array",
      "items": {
        "$ref": "../../../common/1.0/definitions/schema.json#/definitions/otherMembers"
      }
    },
    "provisionalLiquidators": {
      "type": "array",
      "items": {
        "$ref": "../../../common/1.0/definitions/schema.json#/definitions/otherMembers"
      }
    },
    "employees": {
      "type": "array",
      "items": {
        "allOf": [
          {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/person"
          }
        ],
        "properties": {
          "appointmentDate": {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
          },
          "withdrawalDate": {
            "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date"
          }
        },
        "required": [
          "appointmentDate"
        ]
      }
    },
    "receiptNumber": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/receiptNumber"
    },
    "receiptDate": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/date",
      "description": "The date at which this certificate was purchased in DD/MM/YYYY format"
    },
    "signatureName": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/signatureName"
    },
    "qrCode": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/qrCode"
    },
    "authenticationNumber": {
      "$ref": "../../../common/1.0/definitions/schema.json#/definitions/authenticationNumber"
    }
  },
  "required": [
    "entityName",
    "uen",
    "registrationDate",
    "status",
    "statusDate",
    "address",
    "activities",
    "managers",
    "signatureName"
  ]
}

=== Accredifysg/schemata/src/sg/gov/acra/bizfiles/profiles/limited-liability-partnership/1.0/sample-document.json
{
	"entityName": "ZXZTHSI YITU JHHPPZIU YITu",
	"formerNames": [
		"dcba llp"
	],
	"uen": "T19LL0039A",
	"registrationDate": "2019-05-19",
	"status": "Struck Off",
	"statusDate": "2019-10-28",
	"address": {
		"type": "local",
		"streetName": "sea avenue",
		"postalCode": "424242",
		"houseNumber": "20b",
		"invalidReason": "ACRA mail to this address was returned undelivered on 22/12/2017."
	},
	"changeOfNameDate": "2011-04-20",
	"changeOfAddressDate": "2011-04-20",
	"annualDeclarationDate": "2011-03-31",
	"activities": [
		{
			"name": "FOOD FISH FARMS (03201)",
			"description": "SALES OF ACCOUNTING SOFTWARE, HARDWARE & ACCESSORIES"
		},
		{
			"name": "BOOK-KEEPING SERVICES (69202)",
			"description": "BOOKKEEPING & ACCOUNTING SOFTWARE CONSULTANCY SERVICE"
		}
	],
	"partners": [
		{
			"name": "FUFUFUFU",
			"id": "KJH123456",
			"nationality": "BELARUSSIAN",
			"address": {
				"type": "foreign",
				"address1": "GGFGFHGF",
				"address2": "GHGHG",
				"country": "BE",
				"invalidReason": "ACRA mail to this address was returned undelivered on 03/03/2018."
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-08-11"
		},
		{
			"name": "YZYZ",
			"id": "S7074975J",
			"nationality": "SINGAPORE citizen",
			"address": {
				"type": "local",
				"houseNumber": "646",
				"streetName": "aNG MO KIO AVENUE 6",
				"floor": "12",
				"unit": "12",
				"buildingName": "ANG MO KIO 61",
				"postalCode": "560646"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-21"
		},
		{
			"name": "HS REK GNOGNI",
			"id": "S2015147A",
			"nationality": "SINGAPORE citizen",
			"address": {
				"type": "local",
				"houseNumber": "131",
				"streetName": "tampines street 11",
				"postalCode": "521131"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-21"
		},
		{
			"name": "NAYANA",
			"id": "S2015045I",
			"nationality": "SINGAPORE citizen",
			"address": {
				"type": "local",
				"houseNumber": "747d",
				"streetName": "bedok reservoir crescent",
				"postalCode": "521156"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-21"
		},
		{
			"name": "XIX XHHY HUI IZYXHYU",
			"id": "S1703042F",
			"nationality": "SINGAPORE citizen",
			"address": {
				"type": "local",
				"houseNumber": "156",
				"streetName": "tampines street 12",
				"floor": "08",
				"unit": "23",
				"postalCode": "521156"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-21"
		},
		{
			"name": "ZYIZXZIHP JZYZJHZYUIZY",
			"id": "S7560027E",
			"nationality": "REUNION",
			"address": {
				"type": "local",
				"houseNumber": "20b",
				"streetName": "sea avenue",
				"floor": "01",
				"unit": "02",
				"postalCode": "424242"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-08-11"
		},
		{
			"name": "DSGSG",
			"id": "S7909266E1",
			"nationality": "ALBANIAN",
			"address": {
				"type": "foreign",
				"address1": "BGFDRD",
				"address2": "BGFDRD",
				"country": "AL"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-21"
		},
		{
			"name": "FUFUFUFU",
			"id": "KJH123456",
			"nationality": "BELARUSSIAN",
			"address": {
				"type": "foreign",
				"address1": "GGFGFHGF",
				"address2": "GHGHG",
				"country": "BE",
				"invalidReason": "ACRA mail to this address was returned undelivered on 14/07/2018."
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-08-11",
			"withdrawalDate": "2017-09-22"
		},
		{
			"name": "NAYANA",
			"id": "S2015045I",
			"nationality": "Singapore citizen",
			"address": {
				"type": "local",
				"streetName": "bedok reservoir crescent",
				"postalCode": "474747",
				"houseNumber": "747d"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-08-11",
			"withdrawalDate": "2017-08-11"
		},
		{
			"name": "UIVZU WZIYHI",
			"id": "S7605446J",
			"nationality": "BELGIAN",
			"address": {
				"type": "foreign",
				"address1": "FDSF",
				"address2": "DSFSDF",
				"country": "BL"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-08-11",
			"withdrawalDate": "2017-08-11"
		},
		{
			"name": "DFHZXF XZGSAF",
			"id": "S7988389A",
			"nationality": "BRITISH",
			"address": {
				"type": "local",
				"streetName": "sea avenue",
				"floor": "01",
				"unit": "09",
				"postalCode": "424242",
				"houseNumber": "20b"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-09",
			"withdrawalDate": "2019-10-07"
		},
		{
			"name": "THP XZY PHHYE (XZIXIPIYE)",
			"id": "S2015015G",
			"nationality": "SINGAPORE citizen",
			"address": {
				"type": "foreign",
				"country": "SG",
				"address1": "AFSDSDFSDAFFF",
				"address2": "AFDFDFDFDFDFDFDFDFD"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-08-11",
			"withdrawalDate": "2017-08-11"
		},
		{
			"name": "YIX YHYEXHYE",
			"id": "S7486133D",
			"nationality": "CHINESE",
			"address": {
				"type": "local",
				"streetName": "sea avenue",
				"postalCode": "424242",
				"houseNumber": "20b"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-09",
			"withdrawalDate": "2019-10-07"
		},
		{
			"name": "SPIIZXVIIZX",
			"id": "FDGFDGFDG",
			"nationality": "AMERICAN SAMOA",
			"address": {
				"type": "foreign",
				"country": "AM",
				"address1": "GFDGFDG",
				"address2": "FDGFDG"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-08-11",
			"withdrawalDate": "2017-08-11"
		}
	],
	"managers": [
		{
			"name": "YZYZ",
			"id": "S7074975J",
			"nationality": "SINGAPORE CITIZEN",
			"address": {
				"type": "local",
				"streetName": "ang mo kio avenue 6",
				"floor": "12",
				"unit": "12",
				"postalCode": "560646",
				"houseNumber": "646",
				"buildingName": "ANG MO KIO 61",
				"invalidReason": "ACRA mail to this address was returned undelivered on 28/12/2018."
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-21"
		},
		{
			"name": "HY XHIIXZETZHT HTHY E",
			"id": "S7501116D",
			"nationality": "SINGAPORE P.R.",
			"address": {
				"type": "local",
				"streetName": "woodlands drive 16",
				"floor": "06",
				"unit": "70",
				"postalCode": "730585",
				"houseNumber": "585"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-07-19"
		},
		{
			"name": "AHDPECRSJT",
			"id": "S2015030J",
			"nationality": "SINGAPORE CITIZEN",
			"address": {
				"type": "local",
				"streetName": "central boulevard",
				"postalCode": "018968",
				"houseNumber": "2a"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-21"
		},
		{
			"name": "XIX XHHY HUI IZYXHYU",
			"id": "S201S1703042F5030J",
			"nationality": "SINGAPORE CITIZEN",
			"address": {
				"type": "local",
				"streetName": "tampines street 12",
				"floor": "08",
				"unit": "23",
				"postalCode": "521156",
				"houseNumber": "156"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2019-05-21"
		},
		{
			"name": "ZYIZXZIHP JZYZJHZYUIZY",
			"id": "S7560027E",
			"nationality": "REUNION",
			"address": {
				"type": "local",
				"streetName": "sea avenue",
				"floor": "01",
				"unit": "02",
				"postalCode": "424242",
				"houseNumber": "20b"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-08-11"
		},
		{
			"name": "IHUXHHHIZHS J",
			"id": "S8891086I",
			"nationality": "SINGAPORE CITIZEN",
			"address": {
				"type": "local",
				"streetName": "anson road shell service station",
				"postalCode": "079901",
				"houseNumber": "5",
				"invalidReason": "ACRA mail to this address was returned undelivered on 01/01/2019."
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-07-17",
			"withdrawalDate": "2017-07-19"
		},
		{
			"name": "HY XHIIXZETZHT HTHY E",
			"id": "S7501116D",
			"nationality": "SINGAPORE P.R.",
			"address": {
				"type": "local",
				"streetName": "woodlands drive 16",
				"floor": "06",
				"unit": "70",
				"postalCode": "730585",
				"houseNumber": "585"
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-07-12",
			"withdrawalDate": "2017-07-19"
		}
	],
	"employees": [
		{
			"name": "NAYANA",
			"id": "S2015045I",
			"nationality": "Singapore citizen",
			"address": {
				"type": "local",
				"streetName": "bedok reservoir crescent",
				"postalCode": "474747",
				"houseNumber": "747d",
				"invalidReason": "ACRA mail to this address was returned undelivered on 04/05/2019."
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-05-12"
		},
		{
			"name": "ZHXIYEZ EHHSH",
			"id": "S5445275F",
			"nationality": "SINGAPORE CITIZEN",
			"address": {
				"type": "local",
				"streetName": "tai seng link",
				"postalCode": "534101",
				"houseNumber": "6",
				"invalidReason": "ACRA mail to this address was returned undelivered on 18/10/2019."
			},
			"addressSource": "ACRA",
			"appointmentDate": "2017-05-12",
			"withdrawalDate": "2019-01-31"
		}
	],
	"receiptDate": "2019-10-22",
	"receiptNumber": "ACRAXXXXXXXXXX06",
	"signatureName": "Tan Yong Tat",
	"qrCode": "",
	"authenticationNumber": "IXXXXXXX49"
}
